### PR TITLE
Fix bugs introduced in 580

### LINKED ISSUE #1025: Log
The log window has now been integrated via the user interface. Does this mean that the old log window of Quest has no function? Then I could remove the corresponding buttons and menu items from Quest.

### LINKED ISSUE #1052: JS.setBackground cannot cope with three digit colour
HTML/CSS should be able to cope with #rgb as well as #rrggbb. However, JS.setBackground attempts to slit the string into the three components, and is not built to take the former, resulting in a JS error.

NB: Different versions in playercore.js and paper.js, but neither can handle this.

### LINKED ISSUE #1054: Transcript crashes games online
Enabling a transcript online crashes (freezes) the game.

I seem to remember writing code to handle online transcripts in a dialog popup, but it was long ago and I'm not positive my recollection is correct.

### LINKED ISSUE #1121: enter_verb pattern is set to "Regular expression", should be "Command pattern"
I already have a pending pull request.

I would create one to fix this issue, but I don't want to get any pull requests crossed.

### LINKED ISSUE #1200: WebPlayer - SAVE Command does not save divOutput
Online, if you click the Save button, everything works correctly when you load your saved game.

However, if you enter the SAVE command instead, the game's text is not restored when you load your saved game.

Looks like a possible fix was posted in this thread: https://textadventures.co.uk/forum/quest/topic/5fd2-liccuidcbbf_eiefa/log-im-trying-to-figure-out-how-to-save-the-content-to-a-file#f91f54ac-f3e9-480a-b98b-83db552b4b4e

If I find a fix during testing, I will create a pull request.

### LINKED ISSUE #1202: AllRooms() Does not Work in a Published Game
In Quest 5.8, the function `AllRooms()` was added to return a list of rooms. (And yes: it was me who submitted this.)

The initial `room` object in **English.template** (and every other template) has a new boolean attribute: `isroom` which is set to `true`.

https://github.com/textadventures/quest/blob/f47a55b960082f559053209e1fbae7366e8f3036/WorldModel/WorldModel/Core/Templates/English.template#L12-L14

---
Any other room created is ***supposed*** to have `isroom` added and set to `true` by default -- unless you uncheck the checkbox in the editor.

This works when you play a game from the editor, but any newly created room's `isroom` attribute does not carry over into a published game.

---
image

---
image

---
image

---
### The Issue

 I added `isroom` to the `editor_room` type, thinking it would carry over.

https://github.com/textadventures/quest/blob/f47a55b960082f559053209e1fbae7366e8f3036/WorldModel/WorldModel/Core/CoreEditor.aslx#L19-L21

---
I just now unwittingly happened to use `AllRooms()` in a test game and discovered this issue.

I searched the forum for "AllRooms", but I didn't get any results with anyone talking about this not working.

---
I made an example game, just for this issue. I turned on DevMode and left it on when I published the game. (It still works fine after publishing a game; it just doesn't have the GUI.)

Here is a link to play it from the editor: https://play.textadventures.co.uk/Play.aspx?id=editor/81f17eb0-ebd0-4aa6-981f-828287f15e46%2fAllRooms+Only+Works+in+the+Editor.aslx

image

---
And here is a link to play the published version: https://play.textadventures.co.uk/Play.aspx?id=9f_y-hmjmewmzd2mvrlixg

image

---
As stated, I just discovered this, and I can't think of any possible fixes at this moment.

### LINKED ISSUE #1259: Image in listalias causes errors
https://github.com/textadventures/quest/blob/9e370290d488911f43aae09d0355a05ceeafef90/WorldModel/WorldModel/Core/CoreDescriptions.aslx#L369-L380

---
I modified `GetListDisplayAlias` to use the text processor if an object's `listalias` attribute was defined as a string.

Using an image like `{img:foo.png}` will cause errors when clicking the verb buttons in the pane.

### LINKED ISSUE #1270: An alias including "." doesn't play well with `game.multiplecommands`
If `game.multiplecommands` is `true` and there is a `.` in an object's alias, there will be issues.

> **\> x Mr. XanMag. Take beer. Give beer to Mr. Xanmag**
Nothing out of the ordinary.
I don't understand your command.
You pick it up.
Mr. XanMag thanks you kindly and gives you the **small brass key**.
I don't understand your command.

---
I have a fix based on the code posted by angelwedge in this issue: https://github.com/textadventures/quest/issues/1256#issuecomment-2515559421

I'll submit the PR after a little more testing.

### LINKED ISSUE #1284: AGAIN command should match LCase command to LCase template
Pertex found a bug.

Some of the templates are not all lower-case.

Pertex has a fix:

https://github.com/textadventures/quest/blob/7a0376151cac36728157d2a49827e783777e8c7e/WorldModel/WorldModel/Core/CoreParser.aslx#L126

Change that ☝️ to this 👇 

```c#
    else if (LCase(command) = LCase(Template("Again1")) or LCase(command) = LCase(Template("Again2"))) {
```

---
PR coming right up!

### PR DESCRIPTION
**Pull request by TextMisadventures**
Fix Bugs Introduced in 580
- transcript
  - added missing function to player.js
  - changed desktop player file saving format from HTML to TXT
  - added localStorage functionality for the web player
  - removed in-game transcript viewing
  - automatically uses game name for transcript name when command bar is hidden

Closes #1054 

---
- log
  - restored log window in the desktop player
  - removed ability to view the log in-game

Closes #1025 

---
- AllRooms()
  - fixed by @Pertex

Closes #1202 

---
- AGAIN command
  - some templates are not all lower-case, so the comparison to `LCase(command)` failed sometimes

Fixed by @Pertex 

Closes #1284 

---
- setBackground()
  - fixed by @ThePix

Closes #1052 

---
- enter_verb
  - fix stolen from mrangel forum post

Closes #1121 

---
- save command
  - now uses `saveGame()` when online
  - scrolls when printing saveGameResponse messages

Closes #1200 

---
- DictionaryRemove
  - fixed typo

---
Fix issue with `.` in alias when `game.multiplecommands` is `true`

Closes #1270 

---
- update transcript.md doc

---
Fix issue with GetListDisplayAlias

I modified GetListDisplayAlias to use the text processor if an object's listalias attribute was defined as a string.

Using an image like {img:foo.png} will cause errors when clicking the verb buttons in the pane.

Closes #1259 

---

Tidy up language files

- remove code that "includes" EditorEnglish.aslx when English.aslx is already included

---
Addition submitted by @Pertex

Added option to use custom image in the location bar, complete with editor controls

### CODE REVIEW

**Comment by KVonGit** [comment]
I'm not satisfied with the way the transcripts are accessed online.

- There is a game on the site that acts a page to view, download, or delete the transcripts in your localStorage
- If you choose to view one, the pop-up blocker will cause the window to open with nothing loaded the first time.

**Review by alexwarren — CHANGES_REQUESTED** [review]
This is far too big for me to review I'm afraid - could you please split this into a separate PR for each change? That way we can merge these independently or discuss them separately if needed.

**Comment by KVonGit** [comment]
That's no problem at all. I was just thinking I should do this the other day.

That's the way I had it the first time. I think there 19 of them.

Most of these fixes involve the same files, though; so, submitting them all at once didn't work out well, because each branch had to build off the last to avoid conflicts, and the 19th PR was the equivalent of this one.

I'd like to have them all submitted and ready to go, of course (for days like today, haha), but the only other approach I know of is to submit one fix at a time. When each gets merged (or finalized if not merged), then I'll submit the next. (If you have a better approach, I'd be down for that, of course. I'm not as GitHub-savvy as I'd like to be.)

**Comment by alexwarren** [comment]
I think one fix at a time is the way to go, and I'll try to review them promptly (this next week or so is good while I'm on a break from work).

**Pull request closed without merging**
