### PR TITLE
WFEditorTree.resx Ctrl => Control

### PR DESCRIPTION
**Pull request by TextMisadventures**
For internationalization

### CODE REVIEW

**Review by alexwarren — APPROVED** [review]

**Comment by alexwarren** [comment]
Subsequently editing these in Visual Studio has reset this change, so I'm not sure what it was supposed to do...?

**Comment by KVonGit** [comment]
Odd. It seems to have stuck for Pertex. He said he couldn't build the project at all until after that change, and he's been able to build it successfully ever since.

This is the second or third thing I've noticed that seems to be different between US, UK, and German systems, I think.

**Comment by alexwarren** [comment]
I see. Just Googled and this explains things: https://stackoverflow.com/questions/59245734/language-problems-with-shortcuts-in-resx-files

**Comment by Pertex** [comment]
Is  this problem solved or will it be done with #1306 ?

**Comment by KVonGit** [comment]
> Is this problem solved

I meant to ask you about this, @Pertex. If you clone the `textadventures/quest` repo right now, can you successfully build the project in VS (now that this PR was merged)?

**Comment by Pertex** [comment]
I must change Crtl to Control In Menu.resx

**Pull request merged**
