### PR TITLE
Update Greek.aslx

### PR DESCRIPTION
**Pull request by thanosxxx**
Introduced MasculinePlural etc plural types.
Several fixes.

### CODE REVIEW

**Comment by KVonGit** [comment]
Hello.

I apologize, but I have changed the transcript command's pattern and added two more commands to deal with the transcript.

I wasn't sure if this was correct, so I commented it out before I submitted my pull request.

Here is the code:

```xml
   <!--<template templatetype="command" name="transcript_on_cmd">^κείμενο$</template>
    <template templatetype="command" name="transcript_off_cmd">^κείμενο off$</template>
<template templatetype="command" name="view_transcript_cmd">^(δες|δείξε|) (το |)(κείμενο)$</template>-->
```

---
I just submitted that change in this pull request:

https://github.com/textadventures/quest/pull/963

I don't know which pull request will be merged first.  If I saw this pull request, I would have left Greek.aslx alone, but it is too late now.  If you post the correct code for this, I will add it in after all pull requests have been merged.

Sorry about the trouble!

**Comment by thanosxxx** [comment]
No problem, we'll fix that. I changed the transcript translation, btw:

<template templatetype="command" name="view_transcript_cmd">^(δες | δείξε|)(το |)(ιστορικό)$</template>

I guess transcript on and off means start/stop recording? in that case, 
transcript on ----> ^ιστορικό ενεργό
transcript off ----> ^ιστορικό ανενεργό

**Comment by KVonGit** [comment]
Thanks!

This should be what ends up Greek.aslx, after all the pull requests have been merged:

```xml
<template templatetype="command" name="transcript_on_cmd">^ιστορικό$|^ιστορικό ενεργό$</template>
    <template templatetype="command" name="transcript_off_cmd">^ιστορικό ανενεργό$</template>
    <template templatetype="command" name="view_transcript_cmd">^^(δες|δείξε) (το |)ιστορικό$</template
```

**Comment by KVonGit** [comment]
I have merged your changes into my pull request.  Then, I changed the transcript commands to the correct translations of the current versions.  

So, the pull requests can now be merged in the order which they were submitted.  (The changes in this pull request are now in my Greek.aslx file, too.  So, merging my files after this will make everything behave properly.)

**Pull request merged**
